<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit49e5053452b98cc987f14c500b8d8a40
{
    public static $prefixLengthsPsr4 = array (
        'J' => 
        array (
            'Jackal\\Extension\\UIKit\\' => 23,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Jackal\\Extension\\UIKit\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit49e5053452b98cc987f14c500b8d8a40::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit49e5053452b98cc987f14c500b8d8a40::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit49e5053452b98cc987f14c500b8d8a40::$classMap;

        }, null, ClassLoader::class);
    }
}
